# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 092dbad887426971fc5239d51639c3b5bf46c19e5173a5c0fb19ada469f95ef2d48142993bf03b25d17c61b7e651e3ad732d0daf8e774abcf7fb62dffb06addc

test:
  secret_key_base: 37111b02384a05b73b3bd21c8c9852eaf6c0d2f586b25ded1dc1a8d74ec5845c1c3e9944d4af849bffc3070749f0e6c185224b2f96c4cb18cc3a62d47575d16a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
